In [1]:
import numpy as np

# 기초 문제

## 0으로 구성된 (10,)크기의 벡터 생성

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 0으로 구성된 (3,2) 크기의 행렬 생성

In [4]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 값이 10~19인 벡터 생성

In [5]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## 값이 10~19인 (2,5) 행렬 생성

In [7]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 20에서 30까지 2씩 증가한 벡터 생성

In [22]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

## `array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])`를 반전(첫 번째 요소가 마지막이 됨)해서 생성

In [9]:
vec = np.arange(10,20)
vec[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

## 경계가 1이고 내부가 0인 (10,10) 행렬 생성

In [13]:
z = np.ones((10,10))
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 아래의 행렬 데이터에서 4의 배수 값만을 선택하여 하나의 벡터로 생성
`np.arange(20).reshqpe(4,5)`

In [26]:
z = np.arange(20).reshape(4,5)
z[(z%4 == 0) & (z > 0)]

array([ 4,  8, 12, 16])

## `array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])`에서 12보다 크고 18보다 작은 모든 요소를 추출

In [21]:
z = np.arange(10,20)

cond = (z > 12) & (18 > z)
z[cond]

array([13, 14, 15, 16, 17])

# 심화 문제

## 랜덤 값이 있는 (3,3,3) 생성

In [11]:
np.random.random((3,3,3))

array([[[0.35197725, 0.03382624, 0.2550555 ],
        [0.94005824, 0.9381121 , 0.38068452],
        [0.25340345, 0.06527479, 0.16330281]],

       [[0.89613593, 0.74201086, 0.53599523],
        [0.3622236 , 0.04664611, 0.1226088 ],
        [0.19395493, 0.37704324, 0.34911167]],

       [[0.23995661, 0.96100004, 0.85484382],
        [0.71533789, 0.15133698, 0.74476062],
        [0.29754604, 0.1051324 , 0.09600927]]])

## 랜덤 값이 있는 (10,10) 행렬에서 최소값과 최대값을 찾기

In [12]:
z = np.random.random((10,10))
z_min, z_max = z.min(), z.max() 
z_min, z_max 

(0.004034031866567811, 0.9654147269676551)

## 연산 예측하기
1. 0 * np.nan
2. np.nan == np.nan
3. np.inf > np.nan
4. np.nan > np.inf
5. np.nan - np.nan
6. 0.3 == 3 * 0.1


In [14]:
0 * np.nan

nan

In [15]:
np.nan == np.nan

False

In [16]:
np.inf > np.nan

False

In [17]:
np.inf < np.nan

False

In [18]:
np.nan - np.nan

nan

In [19]:
0.3 == 3*0.1

False

## np.newaxis를 사용하여 (5,)를 (5,1)로 변환하시오

In [27]:
x = np.arange(5)
x.shape

(5,)

In [29]:
x[:, np.newaxis].shape

(5, 1)

## 아래 행렬은 5명의 학생이 3과목 시험 성적이다. 

In [30]:
X = np.random.random_integers(0,100, (5,3))
X

<ipython-input-30-f2a7110f7708>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 100 + 1) instead
  X = np.random.random_integers(0,100, (5,3))


array([[66, 57, 65],
       [14, 70, 61],
       [37, 82, 32],
       [30, 38, 72],
       [99, 43, 41]])

각 학생별 최고 높은 성적

In [32]:
X.max(axis=1)

array([66, 70, 82, 72, 99])

각 과목별 최고 높은 성적

In [33]:
X.max(axis=0)

array([99, 82, 72])